#!/usr/bin/env python

import os, sys, time

while True:
    s = os.popen("acpi").read()
    v = s.split()
    if len(v) >= 5:
        print "\n", s.split()[4],
    else:
        print "charging",
    sys.stdout.flush()
    time.sleep(5)
