#!/usr/bin/env bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
unset BUP_DIR

date
cd $HOME

time bup index --exclude=/home/wstein/.Trash --exclude=/home/wstein/.bup --exclude=/home/wstein/box /home/wstein
time bup save -q --remote=salvus@disk.math.washington.edu: -n pixel /home/wstein


date

exit 0
