#!/usr/bin/env bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
unset BUP_DIR
export BUP_DIR='/media/removable/SD Card/bup_pixel' 


ls "$BUP_DIR"

cd $HOME

time bup index --exclude=/home/wstein/.Trash --exclude=/home/wstein/.bup --exclude=/home/wstein/box /home/wstein
time bup save -n home /home/wstein

exit 0
