#!/usr/bin/env bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
unset BUP_DIR

date
cd $HOME


time bup index --exclude /home/wstein/box --exclude /home/wstein/tmp --exclude /home/wstein/Downloads --exclude /home/wstein/.Trash /home/wstein/

time bup save -q --remote=pixel@05salvus: -n home /home/wstein


date

exit 0
