#!/usr/bin/env python

import os, sys

for url in sys.argv[1:]:
    url = url.replace('/attachment/','/raw-attachment/')
    filename = url.split('/')[-1]
    if os.path.exists(filename):
        os.unlink(filename)
    os.system('wget %s'%url)
    os.system('hg qimport %s'%filename)
    if os.path.exists(filename):
        os.unlink(filename)
        os.system('hg qpush')
    
