#!/usr/bin/python

# By William Stein, January, 2004.

import os, random, string, sys

alpha = '_' + string.lowercase + string.digits

if len(sys.argv) == 1:
    n = 8
else:
    n = int(sys.argv[1])
print ''.join([random.choice(alpha) for _ in range(n)])
    
