#!/usr/bin/env bash

# Make it so right side of trackpad isn't right click.
# This doesn't work -- it makes double tap for right click break
#xinput set-button-map 11 1 1 2 4 5 6 7 8 9

# Enable tinc vpn

sudo /home/wstein/salvus/salvus/data/local/sbin/tincd

sudo mount /mnt/sd

echo 100000 | sudo tee /proc/sys/fs/inotify/max_user_watches
dropbox stop
#dropbox start

#cd $HOME/salvus/salvus
#. salvus-env
#./start_salvus

$HOME/.xprofile


syndaemon -i 1 -m 100 -d -R

synclient  MinSpeed=.02; synclient AccelFactor=.15; synclient MaxSpeed=.5; synclient MaxDoubleTapTime=80; synclient MaxTapTime=80
